[versions]
junit = "5.14.1"
junit-platform = "1.14.1"
slf4j = "2.0.17"
xmlunit = "2.11.0"

[libraries]
jspecify = { module = "org.jspecify:jspecify", version = "1.0.0" }
commons-io = { module = "commons-io:commons-io", version = "2.21.0" }
hamcrest = { module = "org.hamcrest:hamcrest", version = "2.2"}
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }
junit-platform-engine = { module = "org.junit.platform:junit-platform-engine", version.ref = "junit-platform" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
pso-diffx = { module = "org.pageseeder.diffx:pso-diffx", version = "1.3.1" }
pso-xmlwriter = { module = "org.pageseeder.xmlwriter:pso-xmlwriter", version = "1.1.1" }
rhino-engine = { module = "org.mozilla:rhino-engine", version = "1.7.14" }
saxon-he = { module ="net.sf.saxon:Saxon-HE", version = "9.9.1-5" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
xmlunit-core = { module = "org.xmlunit:xmlunit-core", version.ref = "xmlunit"}
xmlunit-matchers = { module = "org.xmlunit:xmlunit-matchers", version.ref = "xmlunit"}

[bundles]
junit = [
    "junit-jupiter-api",
    "junit-platform-launcher",
    "junit-platform-engine"
]

[plugins]
jreleaser = { id = "org.jreleaser", version = "1.21.0" }